# Prevent bundle install to use "--deployment", because it will lead to Gemfile.lock conflicts.
# See https://groups.google.com/forum/#!msg/travis-ci/XID21_FwgX8/Dbiv3wDUTZwJ
bundler_args: ""

# Fixes a rubygems bug that causes failures on Travis CI
# See https://github.com/bundler/bundler/issues/2784
before_install:
  - gem update --system 2.2.1
  - gem --version
language: ruby
rvm:
  - 1.9.3
  - 1.8.7
script: "bundle exec rake spec"
env:
  - PUPPET_VERSION=3.0.1
  - PUPPET_VERSION=3.1.0
